"""PLAT-654 fix bg readings post timeout

Revision ID: 3153188409e2
Revises: 6389580aa4c2
Create Date: 2020-11-13 16:48:26.346134

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "3153188409e2"
down_revision = "6389580aa4c2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_hba1c_reading_measured_timestamp"),
        "hba1c_reading",
        ["measured_timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_hba1c_reading_patient_id"),
        "hba1c_reading",
        ["patient_id"],
        unique=False,
    )
    op.drop_index("hba1c_patient_id", table_name="hba1c_reading")
    op.drop_index("hba1c_reading_measured_ts", table_name="hba1c_reading")
    op.create_foreign_key(
        "hba1c_reading_patient_id", "hba1c_reading", "patient", ["patient_id"], ["uuid"]
    )
    op.create_index(
        op.f("ix_reading_measured_timestamp"),
        "reading",
        ["measured_timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reading_patient_id"), "reading", ["patient_id"], unique=False
    )
    op.create_index(
        "reading_unique_idx",
        "reading",
        [
            "blood_glucose_value",
            "units",
            "measured_timestamp",
            "measured_timezone",
            "patient_id",
        ],
        unique=True,
    )
    op.drop_index("reading_measured_ts", table_name="reading")
    op.drop_index("reading_patient_id", table_name="reading")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("reading_patient_id", "reading", ["patient_id"], unique=False)
    op.create_index(
        "reading_measured_ts", "reading", ["measured_timestamp"], unique=False
    )
    op.drop_index("reading_unique_idx", table_name="reading")
    op.drop_index(op.f("ix_reading_patient_id"), table_name="reading")
    op.drop_index(op.f("ix_reading_measured_timestamp"), table_name="reading")
    op.drop_constraint("hba1c_reading_patient_id", "hba1c_reading", type_="foreignkey")
    op.create_index(
        "hba1c_reading_measured_ts",
        "hba1c_reading",
        ["measured_timestamp"],
        unique=False,
    )
    op.create_index("hba1c_patient_id", "hba1c_reading", ["patient_id"], unique=False)
    op.drop_index(op.f("ix_hba1c_reading_patient_id"), table_name="hba1c_reading")
    op.drop_index(
        op.f("ix_hba1c_reading_measured_timestamp"), table_name="hba1c_reading"
    )
    # ### end Alembic commands ###
