"""empty message

Revision ID: 5eadddc831f2
Revises: ab54f0b42094
Create Date: 2018-03-28 09:02:40.503510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eadddc831f2'
down_revision = 'ab54f0b42094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('dose_uuid', table_name='dose')
    op.add_column('patient', sa.Column('suppress_reading_alerts_from', sa.DateTime(), nullable=True))
    op.drop_index('prandial_tag_uuid', table_name='prandial_tag')
    op.add_column('reading', sa.Column('snoozed', sa.Boolean(), nullable=False))
    op.drop_index('reading_patient_id', table_name='reading')
    op.drop_index('reading_uuid', table_name='reading')
    op.drop_index('reading_metadata_uuid', table_name='reading_metadata')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('reading_metadata_uuid', 'reading_metadata', ['uuid'], unique=True)
    op.create_index('reading_uuid', 'reading', ['uuid'], unique=True)
    op.create_index('reading_patient_id', 'reading', ['patient_id'], unique=False)
    op.drop_column('reading', 'snoozed')
    op.create_index('prandial_tag_uuid', 'prandial_tag', ['uuid'], unique=True)
    op.drop_column('patient', 'suppress_reading_alerts_from')
    op.create_index('dose_uuid', 'dose', ['uuid'], unique=True)
    # ### end Alembic commands ###
