"""empty message

Revision ID: 87bae830fb1e
Revises: d8a8dd9d1055
Create Date: 2018-06-13 11:03:29.939147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87bae830fb1e'
down_revision = 'd8a8dd9d1055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column(
        'current_amber_alert', sa.Boolean(), nullable=True))
    op.alter_column('patient', 'current_red_alert',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patient', 'current_red_alert',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    op.drop_column('patient', 'current_amber_alert')
    # ### end Alembic commands ###
