"""empty message

Revision ID: 8fdfb572fd2b
Revises: 1b7f325e8f0e
Create Date: 2018-06-12 09:58:53.076130

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8fdfb572fd2b'
down_revision = '1b7f325e8f0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('red_alert',
        sa.Column('uuid', sa.String(length=36), nullable=False),
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.Column('created_by_', sa.String(), nullable=False),
        sa.Column('modified', sa.DateTime(), nullable=False),
        sa.Column('modified_by_', sa.String(), nullable=False),
        sa.Column('dismissed', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('uuid')
    )
    op.drop_constraint('reading_alert', 'reading', type_='foreignkey')
    op.drop_table('alert')
    op.add_column('reading', sa.Column('red_alert_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'reading', 'red_alert', ['red_alert_id'], ['uuid'])
    op.drop_column('reading', 'alert_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reading', sa.Column('alert_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reading', type_='foreignkey')
    op.create_foreign_key('reading_alert', 'reading', 'alert', ['alert_id'], ['uuid'])
    op.drop_column('reading', 'red_alert_id')
    op.create_table('alert',
        sa.Column('uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column('modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column('dismissed', sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column('created_by_', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('modified_by_', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('uuid', name='alert_pkey')
    )
    op.drop_table('red_alert')
    # ### end Alembic commands ###
