"""empty message

Revision ID: 92cb53bbc59b
Revises: f0b1cca0e291
Create Date: 2018-02-01 23:25:35.788059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92cb53bbc59b'
down_revision = 'f0b1cca0e291'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_banding',
                    sa.Column('uuid', sa.String(length=36), nullable=False),
                    sa.Column('created', sa.DateTime(), nullable=False),
                    sa.Column('modified', sa.DateTime(), nullable=False),
                    sa.Column('description', sa.String(length=20), nullable=False),
                    sa.PrimaryKeyConstraint('uuid')
                   )

    op.create_table('reading_banding_rule',
                    sa.Column('uuid', sa.String(length=36), nullable=False),
                    sa.Column('created', sa.DateTime(), nullable=False),
                    sa.Column('modified', sa.DateTime(), nullable=False),
                    sa.Column('minimum_value', sa.Float(), nullable=True),
                    sa.Column('maximum_value', sa.Float(), nullable=True),
                    sa.Column('prandial_tag_id', sa.String(length=36), nullable=True),
                    sa.Column('reading_banding_id', sa.String(length=36), nullable=True),
                    sa.ForeignKeyConstraint(['prandial_tag_id'], ['prandial_tag.uuid'], ),
                    sa.ForeignKeyConstraint(['reading_banding_id'], ['reading_banding.uuid'], ),
                    sa.PrimaryKeyConstraint('uuid')
                   )

    op.add_column('reading', sa.Column('reading_banding_id', sa.String(length=36), nullable=True))
    op.create_foreign_key('reading_reading_banding_id_fkey', 'reading', 'reading_banding', ['reading_banding_id'], ['uuid'])


def downgrade():

    op.drop_constraint('reading_reading_banding_id_fkey', 'reading', type_='foreignkey')
    op.drop_column('reading', 'reading_banding_id')

    op.drop_table('reading_banding_rule')
    op.drop_table('reading_banding')


