"""empty message

Revision ID: aec5b45a6424
Revises: 
Create Date: 2017-12-21 12:38:37.309005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aec5b45a6424'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prandial_tag',
                    sa.Column('uuid', sa.String(length=36), nullable=False),
                    sa.Column('created', sa.DateTime(), nullable=False),
                    sa.Column('modified', sa.DateTime(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('value', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('uuid')
                   )

    op.create_table('reading_metadata',
                    sa.Column('uuid', sa.String(length=36), nullable=False),
                    sa.Column('created', sa.DateTime(), nullable=False),
                    sa.Column('modified', sa.DateTime(), nullable=False),
                    sa.Column('meter_serial_number', sa.String(), nullable=False),
                    sa.Column('meter_model', sa.String(), nullable=False),
                    sa.Column('manufacturer', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('uuid')
                   )

    op.create_table('reading',
                    sa.Column('uuid', sa.String(length=36), nullable=False),
                    sa.Column('created', sa.DateTime(), nullable=False),
                    sa.Column('modified', sa.DateTime(), nullable=False),
                    sa.Column('patient_id', sa.String(length=36), nullable=False),
                    sa.Column('blood_glucose_value', sa.Float(), nullable=False),
                    sa.Column('units', sa.String(), nullable=False),
                    sa.Column('measured_timestamp', sa.DateTime(), nullable=False),
                    sa.Column('prandial_tag_id', sa.String(length=36), nullable=True),
                    sa.Column('reading_metadata_id', sa.String(length=36), nullable=True),
                    sa.Column('measured_timezone', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['prandial_tag_id'], ['prandial_tag.uuid'], ),
                    sa.ForeignKeyConstraint(['reading_metadata_id'], ['reading_metadata.uuid'], ),
                    sa.PrimaryKeyConstraint('uuid')
                   )

    op.create_table('dose',
                    sa.Column('uuid', sa.String(length=36), nullable=False),
                    sa.Column('created', sa.DateTime(), nullable=False),
                    sa.Column('modified', sa.DateTime(), nullable=False),
                    sa.Column('amount', sa.Float(), nullable=False),
                    sa.Column('reading_id', sa.String(length=36), nullable=True),
                    sa.Column('medication_id', sa.String(length=36), nullable=False),
                    sa.ForeignKeyConstraint(['reading_id'], ['reading.uuid'], ),
                    sa.PrimaryKeyConstraint('uuid')
                   )

    op.create_table('note',
                    sa.Column('uuid', sa.String(length=36), nullable=False),
                    sa.Column('created', sa.DateTime(), nullable=False),
                    sa.Column('modified', sa.DateTime(), nullable=False),
                    sa.Column('creator', sa.String(length=36), nullable=False),
                    sa.Column('content', sa.String(), nullable=False),
                    sa.Column('reading_id', sa.String(length=36), nullable=True),
                    sa.Column('added_timestamp', sa.DateTime(), nullable=False),
                    sa.Column('added_timezone', sa.Integer(), nullable=False),
                    sa.Column('visible_to_patient', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['reading_id'], ['reading.uuid'], ),
                    sa.PrimaryKeyConstraint('uuid')
                   )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note')
    op.drop_table('dose')
    op.drop_table('reading')
    op.drop_table('reading_metadata')
    op.drop_table('prandial_tag')
    # ### end Alembic commands ###
